#!/bin/sh

# load local bashrc
if [ -e ~/.bashrc_local ]; then
    echo "Loading ~/.bashrc_local"
    source ~/.bashrc_local
fi

# bash-completion
if [ "$(uname)" == 'Darwin' ]; then
	OS='Mac'
	source $(brew --prefix)/etc/bash_completion
elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
	OS='Linux'
	source /etc/bash_completion.d/*
else
	echo "Your platform ($(uname -a)) is not supported."
	exit 1
fi

# git-completion
source ~/.git-completion.bash

# CLI prompt
PS1="\[\033[32m\]\u@\h \[\033[36m\]\W $ \[\033[0m\]"

# commands with color
alias ls='ls -G'
alias ll='ls -G -lha'
alias la='ls -G -a'
alias grep='grep --color=auto'

# color diff
export LESS='-R'
alias diff='colordiff -u'

# cd extension
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# pwgen with at least one special symbols
alias pwgen='pwgen -y'

# golang
mkdir -p $HOME/go
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# poetry
export PATH="$HOME/.poetry/bin:$PATH"

# check if kubectl is installed
kubectl > /dev/null
if [ $? == 0 ]; then
	# enable completion
	source <(kubectl completion bash)
	# setup KUBECONFIG
	export KUBECONFIG=`ls ~/.kube/configs/* | tr '\n' ':'`
fi

# kubectl alias
alias kc=kubectl
complete -F __start_kubectl kc

# check if stern is installed
stern > /dev/null
if [ $? == 0 ]; then
	# enable completion
	source <(stern --completion=bash)
fi

# disable Zsh warning on macOS
export BASH_SILENCE_DEPRECATION_WARNING=1
