#!/bin/sh

# load local bashrc
if [ -e ~/.bashrc_local ]; then
    echo "Loading ~/.bashrc_local"
    source ~/.bashrc_local
fi

# bash-completion
if [ "$(uname)" == 'Darwin' ]; then
	OS='Mac'
	export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"
	[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"
elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
	OS='Linux'
	source /etc/bash_completion.d/*
else
	echo "Your platform ($(uname -a)) is not supported."
	exit 1
fi

# git-completion
source ~/.git-completion.bash

# CLI prompt
PS1="\[\033[32m\]\u@\h \[\033[36m\]\W $ \[\033[0m\]"

# commands with color
alias ls='ls -G'
alias ll='ls -G -lha'
alias la='ls -G -a'
alias grep='grep --color=auto'

# color diff
export LESS='-R'
alias diff='colordiff -u'

# cd extension
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# pwgen with at least one special symbols
alias pwgen='pwgen -y'

# uuidgen with lowercase
alias uuidgen='uuidgen | tr "[:upper:]" "[:lower:]"'

# golang
mkdir -p $HOME/go
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# poetry
export PATH="$HOME/.poetry/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# check if kubectl is installed
kubectl > /dev/null
if [ $? == 0 ]; then
	# enable completion
	source <(kubectl completion bash)
	# setup KUBECONFIG
	export KUBECONFIG=`ls ~/.kube/configs/* | tr '\n' ':'`
fi

# kubectl alias
alias kc=kubectl
complete -F __start_kubectl kc

# check if stern is installed
stern > /dev/null
if [ $? == 0 ]; then
	# enable completion
	source <(stern --completion=bash)
fi

# disable Zsh warning on macOS
export BASH_SILENCE_DEPRECATION_WARNING=1

# Get iTerm2 function
function iterm2pane() {
	echo $ITERM_SESSION_ID | sed -r 's/w([0-9]+)t([0-9]+)p([0-9]+):.*/\3/g'
}

function cssh() {
	i=`iterm2pane`
	i=$((i+1))
	echo "# iTerm2 pane No.${i}"
	echo "# SSH to ${!i}"
	ssh ${!i}
}
